resource_definition: 
controller_ip: 
thick_lvm_storagepool_name : 
thin_lvm_storagepool_name : 
node:
  - name: 
    ip: 
    drbd_ip: 
    username: 
    password: 
    disk_path: 
    partition_path: 
    network_card:
    vgname: vgtest
    thinpool_vgname: 
    bmc:
      ip:
      username:
      password:
  - name: 
    ip: 
    drbd_ip: 
    username: 
    password: 
    disk_path: 
    network_card:
    vgname: 
    thinpool_vgname: 
    bmc:
      ip:
      username:
      password:
  - name: 
    ip: 
    drbd_ip: 
    username: 
    password: 
    disk_path: 
    network_card:
    vgname: 
    thinpool_vgname: 
    bmc:
      ip:
      username:
      password: